name: Rockstarcrawls
favicon: null
layout_spectrum: 0.24937
typography_spectrum: 0.5712945505511016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ec135a'
    - '#04030b'
    - '#8c8c8f'
    - '#800000'
  brandStrength: 0.3051073139067739
  lightness: 0.24222560762427747
  saturation: 0.13490991317667067
  rhythmicContrast: 0.1492268438450992
purpose: []
